version: '3.8'

services:
  vpn41:
    build: .
    container_name: vpn41
    hostname: vpn41
    restart: always
    networks:
      - vpn41
    ports:
      - "127.0.0.1:8080:8080"

  web:
    build: ./web
    container_name: web
    restart: always
    networks:
      - vpn41
    ports:
      - 443:443
      - 80:80
    links:
      - vpn41
    volumes:
      - /root/volumes/letsencrypt:/etc/letsencrypt
      - /root/volumes/certbot/www:/var/www/certbot
    depends_on:
      - vpn41

  certbot:
    build: ./certbot
    container_name: certbot
    entrypoint: "/opt/certbot/entrypoint.sh"
    depends_on:
      - web
    volumes:
      - /root/volumes/letsencrypt:/etc/letsencrypt
      - /root/volumes/certbot/www:/var/www/certbot
      - /root/volumes/certbot/log:/var/log/letsencrypt

networks:
  vpn41:

