version: '3.8'

services:
  vpn4one_www_site:
    build: ../../www
    container_name: vpn4one-www-site
    hostname: vpn4one-www-site
    restart: always
    networks:
      - vpn4one
    environment:
      - VIRTUAL_HOST=vpn4.one,www.vpn4.one
    ports: 
      - "127.0.0.1:8080:8080"

  nginx-proxy:
    build: ./nginx
    container_name: nginx-proxy
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - vpn4one
    ports:
      - 443:443
      - 80:80
    links:
      - vpn4one_www_site
    volumes:
      - /root/volumes/letsencrypt:/etc/letsencrypt
      - /root/volumes/certbot/www:/var/www/certbot
    depends_on:
      - certbot

  certbot:
    build: ./certbot
    entrypoint: "/opt/certbot/entrypoint.sh"
    volumes:
      - /root/volumes/letsencrypt:/etc/letsencrypt
      - /root/volumes/certbot/www:/var/www/certbot

networks:
  vpn4one:

